### ISSUE TITLE
Segfaults on certain 9th column GFF values

### ISSUE THREAD

**Issue by lijing28101** [arendsee/synder#2]
When I search this GFF file

```
Gm01    phytozomev9_0   gene    27355   28320   .   -   .   Name=Glyma.01g000100;ID=1;Alias=Glyma.01g000100.Wm82.a2.v1;agi_genecode=magnesium%20ion%20binding%2Cthiamin%20pyrophosphate%20binding%2Chydro-lyases%2Ccatalytics%2C2-succinyl-5-enolpyruvyl-6-hydroxy-3-cyclohexene-1-carboxylic-acid%20synthases;ancestorIdentifier=Glyma01g00210.v1.1;Dbxref=AGI_GeneCode:AT1G68890.1
```

with this synteny map

```
Gm01 336 562 KN643195.1 5697 5923 0.747788 +
Gm01 172767 172964 KN645832.1 1444871 1445068 0.497462 +
Gm01 254499 254749 KN645832.1 1415869 1416119 0.640000 +
Gm01 620173 620377 KN645832.1 673645 673849 0.504902 +
Gm01 698546 698755 KN645832.1 657432 657641 0.559809 +
```

and the command

```
synder search -i a.gff -s b.syn
```

I get the error message

```
SKIPPING ENTRY: Synteny map has no contig names 'nding%2Chydro-lyases%2Ccatalytics%2C2-succinyl-5-enolpyruvyl-6-hydroxy-3-cyclohexene-1-carboxylic-acid%20synthases;ancestorIdentifier=Glyma01g00210.v1.1;Dbxref=AGI_GeneCode:AT1G68890.1'
ERROR: Failed to open synteny map ''
```

I am using `Synder v0.17.3`

Here is my system info

```
Linux xxx 3.10.0-327.22.2.el7.x86_64 #1 SMP EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by arendsee** [comment]
This problem is caused by my extremely naive IO handling. The name field is longer than 128 bytes (the buffer size), so parsing is resuming at the 129th byte, which `synder` interprets as the contig name.

Anyway, I'll overhaul the whole IO system sometime soon. In the meantime, you can get `synder` working by reducing the length of the 9th column. You might need to do this anyway, since I'm not sure I'll ever support arbitrary length attribute fields. I'll think about it. I can at least increase the buffer size to 1kb or so.

I'll report back soon.
